server:
  port: 8080
  context-path: /springbootdemo
  tomcat:
    max-threads: 500
management:
  port: 9081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huawei?useUnicode=true&characterEncoding=utf-8
    username: huawei
    password: huawei
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      idle-timeout: 12000
      max-lifetime: 900000
      minimum-idle: 5
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  rabbitmq:
      host: 192.168.66.41
      port: 5672
      username: rhea
      password: rhea
      virtualHost: fincloud
      connectionTimeout: 10000